# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: stephen-ka
# Company: n0cloudlabs

# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. Generate SSH Keys - ssh-keygen -t rsa -N "" -f $(pwd)/id_rsa_vagrant
# 3. vagrant up
# 4. vagrant ssh  //Will connect you to MASTER or use vagrant ssh <servername>
# 5. Once connected to the master, you can ssh into any lab server using keys (without a password) with command: ssh vagrant@<serverhostname>
# 6. vagrant halt //Stops the lab and powers off VMs - Keeps all data
# 7. vagrant destroy -f ////Stops the lab and powers off VMs and DELETES ALL VMs - LOOSE ALL DATA
# Additional boxes can be added from https://app.vagrantup.com/boxes/search
#############################################################################################################################################
#
# Future Items
# 1. Move script to external file, add package manager conditionals.
# 2. Import gpg keys as part of scripts.
# 3. Port forwards all rem'd out due to conflict.  can only forward on one guest.
# 4. Add shared disk for clusters.
# 5. Fix bash profile for remote terminal functionality - run command from terminal manually
#
#   eval `ssh-agent -s`
#   ssh-add
#
#

# Global Definitions
CENTOS7 = "centos/7"
CENTOS8 = "centos/8"
UBUNTU14 = "ubuntu/trusty64"
UBUNTU16 = "ubuntu/xenial64"
UBUNTU18 = "ubuntu/bionic64"
UBUNTU20 = "ubuntu/focal64"
NETSUB = "10.7.100."
MASTERIP = NETSUB + "5"

# MASTER or BASTION Server Definitions (Also Primary Server for vagrant shh)
MASTER_SERVER_CPU = 1
MASTER_SERVER_MEMORY = 1024
MASTER_SERVER_OS = CENTOS7
MASTER_SERVER_NAME = "master"
MASTER_SERVER_ADDDISKSIZE = "2GB"

# LOAD BALANCER Server Definitions - 0 by default for no deployment
LB_SERVER_COUNT = 1
LB_SERVER_CPU = 1
LB_SERVER_MEMORY = 1024
LB_SERVER_OS = CENTOS7
LB_SERVER_NAME = "lb" # This name will be suffixed with a count number

# WEB Server Definitions - 0 by default for no deployment
WEB_SERVER_COUNT = 1
WEB_SERVER_CPU = 1
WEB_SERVER_MEMORY = 512
WEB_SERVER_OS = CENTOS7
WEB_SERVER_NAME = "web" # This name will be suffixed with a count number

# APP Server Definitions - 0 by default for no deployment
APP_SERVER_COUNT = 1
APP_SERVER_CPU = 1
APP_SERVER_MEMORY = 1024
APP_SERVER_OS = CENTOS7
APP_SERVER_NAME = "app" # This name will be suffixed with a count number

# DATABASE Server Definitions - 0 by default for no deployment
DB_SERVER_COUNT = 1
DB_SERVER_CPU = 1
DB_SERVER_MEMORY = 1024
DB_SERVER_OS = CENTOS7
DB_SERVER_NAME = "db" # This name will be suffixed with a count number

# Scripts

# FUTURE USE
$SSHOWN = <<-SCRIPT
chown -R vagrant:vagrant /home/vagrant/.ssh/
SCRIPT

# FUTURE USE
# https://docs.fedoraproject.org/en-US/epel/
$POST_SCRIPT_YUM = <<-SCRIPT
yum upgrade -y
yum install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
yum install gcc kernel-devel kernel-headers dkms make bzip2 perl wget curl vim -y
echo "complete" >> /home/vagrant/postscript.txt
SCRIPT

# FUTURE USE
$POST_SCRIPT_APT = <<-SCRIPT
apt-get update
apt-get upgrade -y
echo "complete" >> /home/vagrant/postscript.txt
SCRIPT

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.ssh.forward_agent = true

  # Install POSTS SCRIPTS on ALL Machines 
  # config.vm.provision "shell", inline: $POST_SCRIPT_YUM


  config.vm.define MASTER_SERVER_NAME + "1", primary: true do |master|
    master.vm.box = CENTOS7
    master.vm.hostname = MASTER_SERVER_NAME + "1"
    master.vm.network :private_network, ip: MASTERIP
    master.vm.disk :disk, size: MASTER_SERVER_ADDDISKSIZE, name: "storage"
    master.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
    master.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
    master.vm.provision "file", source: "./scripts/config", destination: "/home/vagrant/.ssh/config"
    master.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
    master.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
    master.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
    master.vm.provision "shell", inline: "eval $(ssh-agent)"
    master.vm.provision "shell", inline: "ssh-add /home/vagrant/.ssh/id_rsa_vagrant"
    #master.vm.provision "shell", path: "scripts/scripts1.sh"
    #master.vm.provision "shell", path: "scripts/scripts2.sh"
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = MASTER_SERVER_CPU
      vb.memory = MASTER_SERVER_MEMORY
    end
  end
  
    (1..LB_SERVER_COUNT).each do |i|
      config.vm.define LB_SERVER_NAME + "#{i}" do |lb|
      lb.vm.box = LB_SERVER_OS
      lb.vm.hostname = LB_SERVER_NAME + "#{i}"
      lb.vm.network :private_network, ip: NETSUB + "#{i + 10}"
      lb.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
      lb.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
      lb.vm.provision "file", source: "./scripts/config", destination: "/home/vagrant/.ssh/config"
      lb.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
      lb.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
      lb.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
      #lb.vm.provision "shell", path: "scripts/scripts1.sh"
      #lb.vm.provision "shell", path: "scripts/scripts2.sh"
      #lb.vm.network :forwarded_port, guest: 80, host: 8080
      #lb.vm.network :forwarded_port, guest: 443, host: 4343
        lb.vm.provider "virtualbox" do |vb|
          vb.cpus = LB_SERVER_CPU
          vb.memory = LB_SERVER_MEMORY
        end
      end
    end
    (1..WEB_SERVER_COUNT).each do |i|
      config.vm.define WEB_SERVER_NAME + "#{i}" do |web|
      web.vm.box = WEB_SERVER_OS
      web.vm.hostname = WEB_SERVER_NAME + "#{i}"
      web.vm.network :private_network, ip: NETSUB + "#{i + 20}"
      web.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
      web.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
      web.vm.provision "file", source: "./scripts/config", destination: "/home/vagrant/.ssh/config"
      web.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
      web.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
      web.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
        #web.vm.network :forwarded_port, guest: 80, host: 8080
        #web.vm.network :forwarded_port, guest: 443, host: 4343
        web.vm.provider "virtualbox" do |vb|
          vb.cpus = WEB_SERVER_CPU
          vb.memory = WEB_SERVER_MEMORY
        end
      end
    end
    (1..APP_SERVER_COUNT).each do |i|
      config.vm.define APP_SERVER_NAME + "#{i}" do |app|
      app.vm.box = APP_SERVER_OS
      app.vm.hostname = APP_SERVER_NAME + "#{i}"
      app.vm.network :private_network, ip: NETSUB + "#{i + 30}"
      app.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
      app.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
      app.vm.provision "file", source: "./scripts/config", destination: "/home/vagrant/.ssh/config"
      app.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
      app.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
      app.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
      #app.vm.provision "shell", path: "scripts/scripts1.sh"
      #app.vm.provision "shell", path: "scripts/scripts2.sh"
      #app.vm.network :forwarded_port, guest: 80, host: 8080
      #app.vm.network :forwarded_port, guest: 443, host: 4343
        app.vm.provider "virtualbox" do |vb|
          vb.cpus = APP_SERVER_CPU
          vb.memory = APP_SERVER_MEMORY
        end
      end
    end
    (1..DB_SERVER_COUNT).each do |i|
      config.vm.define DB_SERVER_NAME + "#{i}" do |db|
      db.vm.box = DB_SERVER_OS
      db.vm.hostname = DB_SERVER_NAME + "#{i}"
      db.vm.network :private_network, ip: NETSUB + "#{i + 40}"
      db.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
      db.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
      db.vm.provision "file", source: "./scripts/config", destination: "/home/vagrant/.ssh/config"
      db.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
      db.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
      db.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
      #db.vm.provision "shell", path: "scripts/scripts1.sh"
      #db.vm.provision "shell", path: "scripts/scripts2.sh"
      #db.vm.network :forwarded_port, guest: 80, host: 8080
      #db.vm.network :forwarded_port, guest: 443, host: 4343
        db.vm.provider "virtualbox" do |vb|
          vb.cpus = DB_SERVER_CPU
          vb.memory = DB_SERVER_MEMORY
        end
      end
    end
  end