# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: stephen-ka
# Company: n0cloudlabs

# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. Generate SSH Keys - ssh-keygen -t rsa -N "" -f $(pwd)/id_rsa_vagrant
# 3. vagrant up
# 4. vagrant ssh  //Will connect you to MASTER or use vagrant ssh <servername>
# 5. Once connected to the master, you can ssh into any lab server using keys (without a password) with command: ssh vagrant@<serverhostname>
# 6. vagrant halt //Stops the lab and powers off VMs - Keeps all data
# 7. vagrant destroy -f ////Stops the lab and powers off VMs and DELETES ALL VMs - LOOSE ALL DATA
# Additional boxes can be added from https://app.vagrantup.com/boxes/search
#############################################################################################################################################
#
# Future Items
# 1. Move script to external file, add package manager conditionals.
# 2. Import gpg keys as part of scripts.
# 3. Port forwards all rem'd out due to conflict.  can only forward on one guest.
# 4. Add shared disk for clusters.
# 5. Fix bash profile for remote terminal functionality - run command from terminal manually
#
#   eval `ssh-agent -s`
#   ssh-add
#
#

# Global Definitions
CENTOS7 = "centos/7"
CENTOS8 = "centos/8"
UBUNTU14 = "ubuntu/trusty64"
UBUNTU16 = "ubuntu/xenial64"
UBUNTU18 = "ubuntu/bionic64"
UBUNTU20 = "ubuntu/focal64"
NETSUB = "10.7.100."
MASTERIP = NETSUB + "5"

# MASTER or BASTION Server Definitions (Also Primary Server for vagrant shh)
MASTER_SERVER_CPU = 1
MASTER_SERVER_MEMORY = 1024
MASTER_SERVER_OS = CENTOS7
MASTER_SERVER_NAME = "master"
MASTER_SERVER_ADDDISKSIZE = "2GB"

# LOAD BALANCER Server Definitions - 0 by default for no deployment
LB_SERVER_COUNT = 0
LB_SERVER_CPU = 1
LB_SERVER_MEMORY = 1024
LB_SERVER_OS = CENTOS7
LB_SERVER_NAME = "lb" # This name will be suffixed with a count number

# WEB Server Definitions - 0 by default for no deployment
WEB_SERVER_COUNT = 0
WEB_SERVER_CPU = 1
WEB_SERVER_MEMORY = 512
WEB_SERVER_OS = CENTOS7
WEB_SERVER_NAME = "web" # This name will be suffixed with a count number

# APP Server Definitions - 0 by default for no deployment
APP_SERVER_COUNT = 0
APP_SERVER_CPU = 1
APP_SERVER_MEMORY = 1024
APP_SERVER_OS = CENTOS7
APP_SERVER_NAME = "app" # This name will be suffixed with a count number

# DATABASE Server Definitions - 0 by default for no deployment
DB_SERVER_COUNT = 0
DB_SERVER_CPU = 1
DB_SERVER_MEMORY = 1024
DB_SERVER_OS = CENTOS7
DB_SERVER_NAME = "db" # This name will be suffixed with a count number

# Scripts

# FUTURE USE
$SSHOWN = <<-SCRIPT
chown -R vagrant:vagrant /home/vagrant/.ssh/
SCRIPT

# FUTURE USE
# https://docs.fedoraproject.org/en-US/epel/
$POST_SCRIPT_YUM = <<-SCRIPT
yum upgrade -y
yum install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
yum install gcc kernel-devel kernel-headers dkms make bzip2 perl wget curl vim -y
echo "complete" >> /home/vagrant/postscript.txt
SCRIPT

# FUTURE USE
$POST_SCRIPT_APT = <<-SCRIPT
apt-get update
apt-get upgrade -y
echo "complete" >> /home/vagrant/postscript.txt
SCRIPT

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.ssh.forward_agent = true
  # Install POSTS SCRIPTS on ALL Machines 
  config.vm.provision "shell", inline: $POST_SCRIPT_YUM


  config.vm.define MASTER_SERVER_NAME + "1", primary: true do |subconfig|
    subconfig.vm.box = CENTOS7
    subconfig.vm.hostname = MASTER_SERVER_NAME + "1"
    subconfig.vm.network :private_network, ip: MASTERIP
    subconfig.vm.disk :disk, size: MASTER_SERVER_ADDDISKSIZE, name: "storage"
    subconfig.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
    subconfig.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
    subconfig.vm.provision "file", source: "./config", destination: "/home/vagrant/.ssh/config"
    subconfig.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
    subconfig.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
    subconfig.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
    subconfig.vm.provision "shell", inline: "eval $(ssh-agent)"
    subconfig.vm.provision "shell", inline: "ssh-add /home/vagrant/.ssh/id_rsa_vagrant"
    subconfig.vm.provider "virtualbox" do |master|
      master.cpus = MASTER_SERVER_CPU
      master.memory = MASTER_SERVER_MEMORY
    end
  end
  
    (1..LB_SERVER_COUNT).each do |i|
      config.vm.define LB_SERVER_NAME + "#{i}" do |subconfig|
        subconfig.vm.box = LB_SERVER_OS
        subconfig.vm.hostname = LB_SERVER_NAME + "#{i}"
        subconfig.vm.network :private_network, ip: NETSUB + "#{i + 10}"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
        subconfig.vm.provision "file", source: "./config", destination: "/home/vagrant/.ssh/config"
        subconfig.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
        subconfig.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
        subconfig.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
        #subconfig.vm.network :forwarded_port, guest: 80, host: 8080
        #subconfig.vm.network :forwarded_port, guest: 443, host: 4343
        subconfig.vm.provider "virtualbox" do |lb|
          lb.cpus = LB_SERVER_CPU
          lb.memory = LB_SERVER_MEMORY
        end
      end
    end
    (1..WEB_SERVER_COUNT).each do |i|
      config.vm.define WEB_SERVER_NAME + "#{i}" do |subconfig|
        subconfig.vm.box = WEB_SERVER_OS
        subconfig.vm.hostname = WEB_SERVER_NAME + "#{i}"
        subconfig.vm.network :private_network, ip: NETSUB + "#{i + 20}"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
        subconfig.vm.provision "file", source: "./config", destination: "/home/vagrant/.ssh/config"
        subconfig.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
        subconfig.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
        subconfig.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
        #subconfig.vm.network :forwarded_port, guest: 80, host: 8080
        #subconfig.vm.network :forwarded_port, guest: 443, host: 4343
        subconfig.vm.provider "virtualbox" do |web|
          web.cpus = WEB_SERVER_CPU
          web.memory = WEB_SERVER_MEMORY
        end
      end
    end
    (1..APP_SERVER_COUNT).each do |i|
      config.vm.define APP_SERVER_NAME + "#{i}" do |subconfig|
        subconfig.vm.box = APP_SERVER_OS
        subconfig.vm.hostname = APP_SERVER_NAME + "#{i}"
        subconfig.vm.network :private_network, ip: NETSUB + "#{i + 30}"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
        subconfig.vm.provision "file", source: "./config", destination: "/home/vagrant/.ssh/config"
        subconfig.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
        subconfig.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
        subconfig.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
        #subconfig.vm.network :forwarded_port, guest: 80, host: 8080
        #subconfig.vm.network :forwarded_port, guest: 443, host: 4343
        subconfig.vm.provider "virtualbox" do |app|
          app.cpus = APP_SERVER_CPU
          app.memory = APP_SERVER_MEMORY
        end
      end
    end
    (1..DB_SERVER_COUNT).each do |i|
      config.vm.define DB_SERVER_NAME + "#{i}" do |subconfig|
        subconfig.vm.box = DB_SERVER_OS
        subconfig.vm.hostname = DB_SERVER_NAME + "#{i}"
        subconfig.vm.network :private_network, ip: NETSUB + "#{i + 40}"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant", destination: "/home/vagrant/.ssh/id_rsa_vagrant"
        subconfig.vm.provision "file", source: "./id_rsa_vagrant.pub", destination: "/home/vagrant/.ssh/id_rsa_vagrant.pub"
        subconfig.vm.provision "file", source: "./config", destination: "/home/vagrant/.ssh/config"
        subconfig.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa_vagrant.pub >> /home/vagrant/.ssh/authorized_keys"
        subconfig.vm.provision "shell", inline: "chown -R vagrant:vagrant /home/vagrant/.ssh/"
        subconfig.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/config"
        #subconfig.vm.network :forwarded_port, guest: 80, host: 8080
        #subconfig.vm.network :forwarded_port, guest: 443, host: 4343
        subconfig.vm.provider "virtualbox" do |db|
          db.cpus = DB_SERVER_CPU
          db.memory = DB_SERVER_MEMORY
        end
      end
    end
  end